module.exports = [
  {
    id: 'introduction',
    text: 'Introduction',
    url: '/',
    items: [
      { id: 'author', text: 'Author', url: 'https://www.swis.nl/over-ons/bjorn-brala' },
      { id: 'demo', text: 'Demo', url: '/demo.html' },
    ],
  },
  {
    id: 'documentation',
    text: 'Documentation',
    url: '/docs.html',
    items: [
      { id: 'options', text: 'Options', url: '/docs.html' },
      { id: 'items', text: 'Defining menu items', url: '/docs/items.html' },
      { id: 'plugin-commands', text: 'Plugin commands', url: '/docs/plugin-commands.html' },
      { id: 'custom-icons', text: 'Customize icons', url: '/docs/customize.html' },
      { id: 'fontawesome-icons', text: 'FontAwesome icons', url: '/demo/fontawesome-icons.html' },
      { id: 'font-awesome', text: 'Font Awesome support', url: '/docs/font-awesome.html' },
      { id: 'runtime-options', text: 'Runtime options', url: '/docs/runtime-options.html' },
      { id: 'custom-command-types', text: 'Custom command types', url: '/docs/custom-command-types.html' },
      { id: 'events', text: 'Events', url: '/docs/events.html' },
      { id: 'html5-polyfill-docs', text: 'HTML5 polyfill', url: '/docs/html5-polyfill.html' },
    ],
  },
  {
    id: 'demo-gallery',
    text: 'Demo gallery',
    url: '/demo.html',
    items: [
      { id: 'simple-context-menu', text: 'Simple Context Menu', url: '/demo.html' },
      { id: 'fontawesome-icons', text: 'FontAwesome icons', url: '/demo/fontawesome-icons.html' },
      { id: 'accesskeys', text: 'Accesskeys', url: '/demo/accesskeys.html' },
      { id: 'async-create', text: 'Create Context Menu (asynchronous)', url: '/demo/async-create.html' },
      { id: 'async-promise', text: 'Create Context Menu (promise)', url: '/demo/async-promise.html' },
      { id: 'callback', text: "Command's action (callbacks)", url: '/demo/callback.html' },
      { id: 'custom-command', text: 'Custom Command Types', url: '/demo/custom-command.html' },
      { id: 'disabled', text: 'Disabled Command', url: '/demo/disabled.html' },
      { id: 'disabled-callback', text: 'Disabled Callback Command', url: '/demo/disabled-callback.html' },
      { id: 'disabled-changing', text: "Changing Command's disabled status", url: '/demo/disabled-changing.html' },
      { id: 'disabled-menu', text: 'Disabled Menu', url: '/demo/disabled-menu.html' },
      { id: 'dynamic', text: 'Adding new Context Menu Triggers', url: '/demo/dynamic.html' },
      { id: 'dynamic-create', text: 'Create Context Menu on demand', url: '/demo/dynamic-create.html' },
      { id: 'html5-import', text: 'Importing HTML5 menu', url: '/demo/html5-import.html' },
      { id: 'html5-polyfill', text: 'HTML5 polyfill', url: '/demo/html5-polyfill.html' },
      { id: 'html5-polyfill-firefox8', text: 'HTML5 polyfill (Firefox)', url: '/demo/html5-polyfill-firefox8.html' },
      { id: 'input', text: 'Input Commands', url: '/demo/input.html' },
      { id: 'keeping-contextmenu-open', text: 'Keeping the context menu open', url: '/demo/keeping-contextmenu-open.html' },
      { id: 'menu-title', text: 'Menus with titles', url: '/demo/menu-title.html' },
      { id: 'menu-promise', text: 'Menu with promise', url: '/demo/menu-promise.html' },
      { id: 'on-dom-element', text: 'Context Menu on DOM Element', url: '/demo/on-dom-element.html' },
      { id: 'sub-menus', text: 'Submenus', url: '/demo/sub-menus.html' },
      { id: 'sub-menus-promise', text: 'Submenus (promise)', url: '/demo/sub-menus-promise.html' },
      { id: 'trigger-custom', text: 'Custom Activated Context Menu', url: '/demo/trigger-custom.html' },
      { id: 'trigger-hover', text: 'Hover Activated Context Menu', url: '/demo/trigger-hover.html' },
      { id: 'trigger-hover-autohide', text: 'Hover Activated Context Menu With Autohide', url: '/demo/trigger-hover-autohide.html' },
      { id: 'trigger-left-click', text: 'Left-Click Trigger', url: '/demo/trigger-left-click.html' },
      { id: 'trigger-swipe', text: 'Swipe Trigger', url: '/demo/trigger-swipe.html' },
    ],
  },
];
